// data/teachers.js

export const teachers = [
  {
    id: "1",
    name: "মোঃ লোকমান উদ্দীন",
    subject: "ইসলাম শিক্ষা",
    designation: "প্রধান শিক্ষক (ভারপ্রাপ্ত)",
    image: "/teachers/lukman.jpg",
    education: "বি.এ.",
    joinDate: "১৪-০২-২০২৩",
    phone: "০১৮৩৬-২২৫৮৮৬",
    bio: "ধর্মীয় শিক্ষায় অভিজ্ঞ এবং ছাত্রদের নৈতিক উন্নয়নে নিবেদিত।",
    facebook: "https://www.facebook.com/lukman.uddin.865173",
  },
  {
    id: "2",
    name: "আবেদ আলী বাবু",
    subject: "গণিত",
    designation: "সহকারী শিক্ষক",
    image: "/teachers/abed.jpg",
    education: "এম.বি.এ (হিসাব বিজ্ঞান)",
    joinDate: "২৬-১২-২০২২",
    phone: "০১৯৬৬-৪৩০১৪৭",
    bio: "গাণিতিক যুক্তি এবং সমস্যা সমাধানে পারদর্শী শিক্ষক।",
    facebook: "https://www.facebook.com/abedalibabu97",
  },
  {
    id: "3",
    name: "নাজরীন আক্তার",
    subject: "ইংরেজী",
    designation: "সহকারী শিক্ষক",
    image: "/teachers/nazrin.jpg",
    education: "বি.বি.এ (হিসাব বিজ্ঞান)",
    joinDate: "০১-০৮-২০২২",
    phone: "০১৬২৩-৬৮৭০২০",
    bio: "ইংরেজি ভাষা শেখাতে উৎসাহী এবং শিক্ষার্থীদের আত্মবিশ্বাস বাড়াতে সাহায্য করেন।",
    facebook: "https://www.facebook.com/naj.rin.16",
  },
  {
    id: "4",
    name: "সুলতানা আক্তার",
    subject: "সমাজ বিজ্ঞান",
    designation: "সহকারী শিক্ষক",
    image: "/teachers/sultana.jpg",
    education: "বিএসএস (রাষ্ট্রবিজ্ঞান)",
    joinDate: "০৯-০৭-২০২৩",
    phone: "০১৭৬৩-৫৮৪৯৮৬",
    bio: "সমাজ পরিবর্তনের চিন্তাধারা শিক্ষার্থীদের মাঝে ছড়িয়ে দিতে আগ্রহী।",
    facebook: "https://www.facebook.com/sadia.sultana.317512",
  },
  {
    id: "5",
    name: "সোমা আক্তার",
    subject: "ভৌত বিজ্ঞান",
    designation: "সহকারী শিক্ষক",
    image: "/teachers/suma.jpg",
    education: "এমএসসি (গণিত)",
    joinDate: "০১-০৭-২০২৪",
    phone: "০১৮৯৪-৪৪১১৩২",
    bio: "ভৌতবিজ্ঞানের জটিল বিষয় সহজভাবে উপস্থাপন করেন।",
    facebook: "https://www.facebook.com/nurjahanakter.nur.3",
  },
];
