export const studentsData = [
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 1,
    name: "Samira Akther",
    group: "Science",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 2,
    name: "Farhana Akther Mumu",
    group: "Science",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 3,
    name: "Khadijs Akther Mukta",
    group: "Science",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 4,
    name: "Nishat Ara Tofa",
    group: "Science",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 5,
    name: "Sumaya Akther",
    group: "Humanitis",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 6,
    name: "Samia Akther Maisha",
    group: "Humanitis",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 7,
    name: "Sanjida Shuva Sumaya",
    group: "Humanitis",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 8,
    name: "Sadiya Akther Riya",
    group: "Humanitis",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 9,
    name: "Aklima Akther",
    group: "Humanitis",
  },
  {
    id: crypto.randomUUID(),
    class: "Ten",
    roll: 10,
    name: "Khadija Khatun",
    group: "Humanitis",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 1,
    name: "Sumaya Akther Panna",
    group: "Science",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 2,
    name: "khadija Akther",
    group: "Humanities",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 3,
    name: "Israt Afrin Jui",
    group: "Science",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 4,
    name: "Sharmin Akther Shubarna",
    group: "Humanities",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 5,
    name: "Janna Akther",
    group: "Science",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 6,
    name: "Husna Akther",
    group: "Humanities",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 7,
    name: "Rima Akther",
    group: "Humanities",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 9,
    name: "Hasi Akther",
    group: "Humanities",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 11,
    name: "Roma Akther",
    group: "Humanities",
  },
  {
    id: crypto.randomUUID(),
    class: "Nine",
    roll: 12,
    name: "Nahida Akther Rubi",
    group: "Humanities",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 13,
    name: "Sumaya Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 12,
    name: "Khadija Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 7,
    name: "Mili Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 1,
    name: "Sandhi Parvin",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 3,
    name: "Samia Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 5,
    name: "Arpita Amol Das",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 11,
    name: "Payel Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 9,
    name: "Tisha Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 8,
    name: "Abida Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Eight",
    roll: 4,
    name: "Nafija Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 5,
    name: "Sabina Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 17,
    name: "Rina Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 1,
    name: "Nowratun Norin",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 2,
    name: "Sharia Naunin",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 9,
    name: "Jannatul Ferdows",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 4,
    name: "Taiba Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 8,
    name: "Jannatul Ferdows",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 10,
    name: "Shakila Nusrat",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 12,
    name: "Samia Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 3,
    name: "Jannatul Ferdows",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 13,
    name: "Tasfia Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 7,
    name: "Ruksina Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 11,
    name: "Jamila Khatun",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 20,
    name: "Priti Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 18,
    name: "Irin Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 14,
    name: "Taiba Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 15,
    name: "Halima Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 6,
    name: "Akhi Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Seven",
    roll: 16,
    name: "Raisajjaman Iqra",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 15,
    name: "Halima Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 8,
    name: "Maria Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 9,
    name: "Jannatul Ferdows",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 12,
    name: "Sushanna Bishwas",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 1,
    name: "Jakia Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 4,
    name: "Tasnia Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 10,
    name: "Mayisha Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 11,
    name: "Sathi Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 7,
    name: "Jeny Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 3,
    name: "Khadija Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 13,
    name: "Juma Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 5,
    name: "Khadija Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 16,
    name: "Sadia Akther",
    group: "N/A",
  },
  {
    id: crypto.randomUUID(),
    class: "Six",
    roll: 6,
    name: "Jonaki Akther",
    group: "N/A",
  },
];
